[tool.poetry]
name = "preprocess"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
pika = "^1.3.2"
unstructured = "^0.12.3"
qdrant-client = "^1.7.2"
openai = "~0.28"
lakefs = "^0.3.0"
python-docx = "^1.1.0"
elasticsearch = "^8.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
