[project]
name = "sr_analytics_backends_migrations"
version = "0.1.0"
description = "Alembic database migrations for sr_analytics database"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=1.10.5",
    "sqlalchemy>=1.4.23",
    "alembic>=1.7.4",
    "python-jose>=3.3.0",
    "python-multipart>=0.0.5",
    "bcrypt>=3.2.0",
    "asyncpg>=0.27.0",
    "databases>=0.5.3",
    "pydantic-settings",       
    "psycopg2-binary>=2.9.0"
     # or use: "psycopg[binary]>=3.1.0" for psycopg3
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["versions"]

[tool.uv.workspace]
# Explicitly disable workspace mode for this project
# Note that we depend on the presence of a '.uv-no-workspace' file here to isolate ourselves from the main repo.
# All because the main repo's toplevel pyproject.toml excludes toshiba_backends.
# It's a mess, and someone with more knowledge of ip and uv needs to fix it.
members = []