[project]
name = "fastapi-logger"
version = "0.1.0"
description = "Enhanced logging utility for FastAPI applications with AWS CloudWatch integration"
readme = "README.md"
requires-python = "==3.11.11"
dependencies = [
    "boto3>=1.37.16",
]