{{- if .Values.qdrant.internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elevaite.fullname" . }}-qdrant
  labels:
    {{- include "elevaite.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  type: {{ .Values.qdrant.internal.service.type }}
  ports:
    - port: 6333
      targetPort: http
      protocol: TCP
      name: http
    - port: 6334
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "elevaite.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
{{- end }}
