name: PR Preview - Cleanup

on:
  pull_request:
    types: [closed]
    branches:
      - testing

jobs:
  cleanup-preview:
    uses: iopexses/elev8s/.github/workflows/reusable-cleanup-preview.yml@on-prem
    with:
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}