# IMPORTANT:
# This workflow should never be called on the develop branch.
# However, GitHub requires that we retain a skeleton in place because it determines the UI access based on the primary branch.

name: TGCS - Deploy to PR Preview

on:
  # Automatic deploy on pull-request to main or release branch
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ tgcs-main, tgcs-release ]

concurrency:
  # don't allow concurrent builds to same PR env, but separate PRs are allowed
  group: tgcs-pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  wrong-workflow-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Block execution on non-tgcs branches
        run: |
          # Issue special GitHub error message that appears as an Annotation on the failed workflow.
          echo "::error::‚ùå WRONG BRANCH SELECTED. Only run TGCS workflows from TGCS branches (tgcs-main, tgcs-release, or feature branches)."
          exit 1
